default_params:
  SEED: 2023
  HEIGHT: 512
  WIDTH: 512
  NUM_IMAGES_PER_PROMPT: 1
  NUM_INFERENCE_STEPS: 50
  GUIDANCE_SCALE: 7.5
  MARGIN_BORDER: 20
  BANNER_H: 800
  BANNER_W: 1360
  NEGATIVE_PROMPT: ""
  
  

loader_params:
  input_directory: "assets"
  default_prompts: [
    "A soft gradient background blending from light blue to white, with random geometric shapes like squares, circles, and hexagons in lighter shades floating gently across the design",
    "A light beige background with a Christmas wreath made of small grocery icons, like fruits, vegetables, and bread. The wreath is minimal, with red and green accents for a festive feel.",
    "A gradient background shifting from deep red to gold, with a small grocery bag icon in the bottom-right corner. The bag contains Diwali essentials like sweets and dry fruits, surrounded by a minimal rangoli pattern for a festive and elegant design"
    ]
